language: node_js
node_js:
- 12
services:
- docker
before_install:
- './.travis/main.sh'
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
jdk:
- oraclejdk8
script:
- npm install && npm test && npm run build && npm run zip
- make image
- make image-branch
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  - provider: releases
    api_key:
      secure: anepYJFH07IyZFwHgFzByakbq6RDz8t67MTHhMd/A0m8m2cIPectsErr6QL3tcmEL7xkzMBz8w0e3oaqaBGjRXnowBlqtnuqoCQHgZz3onu4c9ZYoWSfw5SAqXjXI5xkOoquZ4pY5Se9X10UL5yyOOPXDqDDmU6bZnNdczd2vBtEgdcWVJKw8UOd+DrjQpQx8JB2wGD7/7ufeQn06V8GDZfHOY4uF1/LqmuNunHqD17OcV+oU+ZIG40MPhMIHTKWlSRg15IGpuAXdRa3hygeWfMGEb/uFVSW+egV+5Gp9/+dkbRcB25CAEdrgSGO2px/j0zQhBvClhdrSB9SucbRhnOCXFcfIVyiHAfoeP9h3/aW+KN/4/N+j9BAQRnpxRJE5E1xRqqkAvrO6rYSSBCKsBgj+w/Kf6JvNxQuQe6CG6CX4DEBJ6TmS7B/2uxGNwva1mTLAXrpgBjafd2eIMoXZgn1arA8auwlZjrBJdL6a4y3ahW3fFEe+bonTMYDYLkWRCftE8+bHEEHRV0F8eVIPypYtJ88NiWi6RL//VdaYNb5kur72npLyKN0lrlYLFVXqW5A27Iyn7lebD5uhUpXRLiYL3rzNs1usgwnwNEB9+PrmJ8BnnmPwRyEa+sACa68+HvV9Rs2oEC8QbYXtY+qwEBtnDvll3sg5siuRcY/JM0=
    file: ./build/app.zip
    skip_cleanup: true
    on:
      repo: aperture-sh/navigator
      tags: true
  - provider: script
    script: make push-image
    on:
      branch: master
  - provider: script
    script: make push-image-branch
    on:
      all_branches: true
